### ISSUE TITLE
Readme and switching away from JDAUtils

### ISSUE THREAD

**Issue by adamint** [CodeFromCirc/Thonkery#1]
I don't see a readme, and I believe your current command system is rather inefficient and I'm willing to make a pull to request to change it to a proper, customizable system.

Two, what else would you like me to do, in terms of documentation, features, or code style?

**Comment by CodeFromCirc** [comment]
1. The readme is coming soon as I am a bit busy w/ other projects
2. You are welcome to submit a PR and commit it here
3. The features are still being decided on

**Comment by adamint** [comment]
#2

**Comment by CodeFromCirc** [comment]
[commit here](https://github.com/CodeFromCirc/Thonkery/commit/f48cbf6601f076f9fd874dea979e9c7fe424242a) everything done so this issue is closed.
